export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = "GET_INGREDIENTS_FAILED";

export const GET_CONSTRUCTOR_LIST_RANDOM: 'GET_CONSTRUCTOR_LIST_RANDOM' = "GET_CONSTRUCTOR_LIST_RANDOM";
export const SET_CONSTRUCTOR_LIST_BUN: 'SET_CONSTRUCTOR_LIST_BUN' = "SET_CONSTRUCTOR_LIST_BUN";
export const RESET_CONSTRUCTOR_LIST: 'RESET_CONSTRUCTOR_LIST' = "RESET_CONSTRUCTOR_LIST";
export const ADD_CONSTRUCTOR_LIST_MAIN_TO_INDEX: 'ADD_CONSTRUCTOR_LIST_MAIN_TO_INDEX' =
  "ADD_CONSTRUCTOR_LIST_MAIN_TO_INDEX";
export const MOVE_CONSTRUCTOR_LIST_MAIN_INDEX_TO_INDEX: 'MOVE_CONSTRUCTOR_LIST_MAIN_INDEX_TO_INDEX' =
  "MOVE_CONSTRUCTOR_LIST_MAIN_INDEX_TO_INDEX";

export const DELETE_CONSTRUCTOR_LIST_ITEM_MAIN: 'DELETE_CONSTRUCTOR_LIST_ITEM_MAIN' =
  "DELETE_CONSTRUCTOR_LIST_ITEM_MAIN";

export const POST_ORDER_REQUEST: 'POST_ORDER_REQUEST' = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS' = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILED: 'POST_ORDER_FAILED' = "POST_ORDER_FAILED";

export const SET_MODAL_DATA: 'SET_MODAL_DATA' = "SET_MODAL_DATA";
export const RESET_MODAL_DATA: 'RESET_MODAL_DATA' = "RESET_MODAL_DATA";

export const SET_TAB_BAR_CURRENT: 'SET_TAB_BAR_CURRENT' = "SET_TAB_BAR_CURRENT";
export const UPDATE_TAB_BAR_CURRENT: 'UPDATE_TAB_BAR_CURRENT' = "UPDATE_TAB_BAR_CURRENT";

export const POST_FORGOT_PASSWORD_REQUEST: 'POST_FORGOT_PASSWORD_REQUEST' = "POST_FORGOT_PASSWORD_REQUEST";
export const POST_FORGOT_PASSWORD_SUCCESS: 'POST_FORGOT_PASSWORD_SUCCESS' = "POST_FORGOT_PASSWORD_SUCCESS";
export const POST_FORGOT_PASSWORD_FAILED: 'POST_FORGOT_PASSWORD_FAILED' = "POST_FORGOT_PASSWORD_FAILED";

export const POST_LOGIN_REQUEST: 'POST_LOGIN_REQUEST' = "POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS: 'POST_LOGIN_SUCCESS' = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED: 'POST_LOGIN_FAILED' = "POST_LOGIN_FAILED";

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = "GET_USER_REQUEST";
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = "GET_USER_SUCCESS";
export const GET_USER_FAILED: 'GET_USER_FAILED' = "GET_USER_FAILED";

export const PATCH_USER_REQUEST: 'PATCH_USER_REQUEST' = "PATCH_USER_REQUEST";
export const PATCH_USER_SUCCESS: 'PATCH_USER_SUCCESS' = "PATCH_USER_SUCCESS";
export const PATCH_USER_FAILED: 'PATCH_USER_FAILED' = "PATCH_USER_FAILED";

export const SET_USER_DATA: 'SET_USER_DATA' = "SET_USER_DATA";
export const SET_AUTORIZATION_DATA: 'SET_AUTORIZATION_DATA' = "SET_AUTORIZATION_DATA";
export const RESET_USER_DATA: 'RESET_USER_DATA' = "RESET_USER_DATA";

export const POST_REGISTER_REQUEST: 'POST_REGISTER_REQUEST' = "POST_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS: 'POST_REGISTER_SUCCESS' = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILED: 'POST_REGISTER_FAILED' = "POST_REGISTER_FAILED";

export const POST_RESET_PASSWORD_REQUEST: 'POST_RESET_PASSWORD_REQUEST' = "POST_RESET_PASSWORD_REQUEST";
export const POST_RESET_PASSWORD_SUCCESS: 'POST_RESET_PASSWORD_SUCCESS' = "POST_RESET_PASSWORD_SUCCESS";
export const POST_RESET_PASSWORD_FAILED: 'POST_RESET_PASSWORD_FAILED' = "POST_RESET_PASSWORD_FAILED";

export const POST_TOKEN_REQUEST: 'POST_TOKEN_REQUEST' = "POST_TOKEN_REQUEST";
export const POST_TOKEN_SUCCESS: 'POST_TOKEN_SUCCESS' = "POST_TOKEN_SUCCESS";
export const POST_TOKEN_FAILED: 'POST_TOKEN_FAILED' = "POST_TOKEN_FAILED";

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = "WS_CONNECTION_START";
export const WS_CONNECTION_FINISH: 'WS_CONNECTION_FINISH' = "WS_CONNECTION_FINISH";
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = "WS_CONNECTION_ERROR";
export const WS_SET_SOCKET: 'WS_SET_SOCKET' = "WS_SET_SOCKET";
export const WS_CONNECTION_CLOSED:'WS_CONNECTION_CLOSED' = "WS_CONNECTION_CLOSED";

export const WS_GET_MESSAGE:'WS_GET_MESSAGE' = "WS_GET_MESSAGE";
export const WS_SEND_MESSAGE:'WS_SEND_MESSAGE' = "WS_SEND_MESSAGE";
